hugoVersion:
  extended: true
  min: "0.115.2"

imports:
  - path: "github.com/gethugothemes/hugo-modules/search"
  - path: "github.com/gethugothemes/hugo-modules/pwa"
  - path: "github.com/gethugothemes/hugo-modules/images"
  - path: "github.com/gethugothemes/hugo-modules/icons/font-awesome"
  - path: "github.com/gethugothemes/hugo-modules/components/render-link"
  - path: "github.com/gethugothemes/hugo-modules/shortcodes/button"
  - path: "github.com/gethugothemes/hugo-modules/seo-tools/basic-seo"
  - path: "github.com/gethugothemes/hugo-modules/seo-tools/site-verifications"
  - path: "github.com/gethugothemes/hugo-modules/table-of-contents"
